-- CREATE TABLE EmployeeDemographics (
--     EmployeeID INT PRIMARY KEY,
--     FirstName VARCHAR(50),
--     LastName VARCHAR(50),
--     Age INT,
--     Gender VARCHAR(50),
-- );

-- CREATE TABLE EmployeeSalaries (
--     EmployeeID INT PRIMARY KEY,
--     JobTitle VARCHAR(50),
--     Salary INT,
--     Bonus INT
-- );
